image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.10_7_1.10.1_3.5.0

stages:
  - test

before_script:
  - sbt sbtVersion

test:
  stage: test
  script:
    - sbt clean coverage test coverageReport
  artifacts:
    paths:
      - target/scala-*/scoverage-*
